"""Generate python/rude/core/node_types.py from tree-sitter-python grammar.

Run: uv run python scripts/generate_node_types.py
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from rude._rust import node_type_names

TARGET = Path(__file__).resolve().parent.parent / "python" / "rude" / "core" / "node_types.py"


def make_const_name(node_type: str) -> str:
    """Convert a node type string to a Python constant name.

    Examples: "call" -> "CALL", "class_definition" -> "CLASS_DEFINITION"
    """
    return node_type.upper()


def generate() -> str:
    names = sorted(set(node_type_names()))

    member_lines: list[str] = []
    for name in names:
        const = make_const_name(name)
        member_lines.append(f'    {const} = "{name}"')

    return textwrap.dedent("""\
        # AUTO-GENERATED by scripts/generate_node_types.py — DO NOT EDIT
        #
        # Regenerate: uv run python scripts/generate_node_types.py

        from __future__ import annotations

        from enum import StrEnum


        class NodeType(StrEnum):
            \"\"\"Tree-sitter node type constants.

            Used in ``Rule.node_types`` for autocomplete and validation::

                from rude import Rule, NodeType

                class MyRule(Rule):
                    node_types = {{NodeType.CALL}}
            \"\"\"

        {members}


        VALID_NODE_TYPES: frozenset[NodeType] = frozenset(NodeType)
        \"\"\"All named node types from tree-sitter-python's grammar.\"\"\"

        __all__ = ["NodeType", "VALID_NODE_TYPES"]
    """).format(
        members="\n".join(member_lines),
    )


def main() -> None:
    content = generate()
    TARGET.write_text(content)
    print(f"Generated {TARGET} ({len(set(node_type_names()))} node types)")


if __name__ == "__main__":
    main()
